---

## data generation
classification_type: 'group' # binary, group, individual
mode_data: 'STRATIFIED' # 'STRATIFIED', 'SINGLE_ATTACK', 'EXCLUDE_SINGLE_ATTACK', 'HALF_BENIGN', 'RANDOM'
normalization: 'StandardScaler'
feature_extractor: None 
max_partitions_size: 2500
val_ratio: 0.2

##
num_rounds: 5
num_clients: 10
batch_size: 64
num_classes: 8
num_clients_per_round_fit: 4
num_clients_per_round_eval: 2
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1

# model:
#   _target_: model.Net
#   num_classes: ${num_classes}

defaults:
  - model: net
  - strategy: fedavg # points to conf/strategy/fedavg.yaml